//! Audit report generation - markdown and todos output
//!
//! Generates human-readable audit reports with actionable findings.
//! Two output modes:
//! - Full markdown report (`loct audit`)
//! - Actionable todo checklist (`loct audit --todos`)

use std::fmt::Write as _;

use serde::Serialize;

use super::crowd::types::Crowd;
use super::cycles::{ClassifiedCycle, CycleCompilability};
use super::dead_parrots::DeadExport;
use super::health_inputs::{AUDIT_BASIS, STRUCTURAL_BASIS, counts_as_dead_defect};
use super::health_score::{HealthMetrics, HealthScore, calculate_health_score};
use super::twins::{ExactTwin, TwinClass, omit_from_duplicate_groups};

/// Provenance printed in the human header — same fields `manifest.json` already stores.
#[derive(Debug, Clone)]
pub struct ReportProvenance {
    pub version: String,
    pub generated_at: String,
    pub root: String,
    pub git_commit: Option<String>,
}

/// Collected audit findings for report generation
#[derive(Debug, Default)]
pub struct AuditFindings {
    pub cycles: Vec<ClassifiedCycle>,
    pub dead_exports: Vec<DeadExport>,
    pub twins: Vec<ExactTwin>,
    pub orphan_files: Vec<OrphanFile>,
    /// Orphans that are artifacts (generated/lockfiles/vendored/fixtures) or
    /// docs — separated from the actionable orphan section by the artifact
    /// fence. A `package-lock.json` is not an "orphan to review".
    pub artifact_orphans: Vec<OrphanFile>,
    /// Orphans that are runtime entrypoints (Cargo `[[bin]]`, package.json
    /// `main`/`bin`, shebang scripts, detected main markers) — no importers
    /// by design. Roots, not orphans to review.
    pub entrypoint_orphans: Vec<OrphanFile>,
    /// Test-role files (`Tests/`, `*Tests/`, `*Tests.swift`, `*Spec.swift`,
    /// plus the existing JS/TS/Rust/Python conventions). Graph roots, not
    /// orphans to review.
    pub test_orphans: Vec<OrphanFile>,
    /// Script-role files (`scripts/`, `*.sh`). Graph roots, not orphans.
    pub script_orphans: Vec<OrphanFile>,
    /// Doc-role files (markdown/rst/txt). Graph roots, not orphans.
    pub doc_orphans: Vec<OrphanFile>,
    /// Manifest-role files (`Package.swift`, `Cargo.toml`, `package.json`, …).
    pub manifest_orphans: Vec<OrphanFile>,
    pub shadow_exports: Vec<ShadowExport>,
    pub crowds: Vec<Crowd>,
    pub total_files: usize,
    pub total_loc: usize,
    /// Filled by `audit_findings` from the snapshot that also wrote `manifest.json`.
    pub provenance: Option<ReportProvenance>,
}

/// Orphan file with no importers
#[derive(Debug, Clone, Serialize)]
pub struct OrphanFile {
    pub path: String,
    pub loc: usize,
}

/// Shadow export - same symbol with some dead instances
#[derive(Debug, Clone, Serialize)]
pub struct ShadowExport {
    pub name: String,
    pub total_locations: usize,
    pub dead_locations: usize,
}

fn write_role_orphan_rollup(out: &mut String, label: &str, files: &[OrphanFile]) {
    if files.is_empty() {
        return;
    }
    let loc: usize = files.iter().map(|file| file.loc).sum();
    writeln!(out, "- {label}: {} files, {} LOC", files.len(), loc).unwrap();
}

fn format_symbol_location(file: &str, line: Option<usize>) -> String {
    match line {
        Some(n) if n > 0 => format!("{file}:{n}"),
        _ => file.to_string(),
    }
}

fn write_header(out: &mut String, findings: &AuditFindings) {
    writeln!(out, "# Codebase Audit Report\n").unwrap();
    let version = findings
        .provenance
        .as_ref()
        .map(|p| p.version.as_str())
        .unwrap_or(crate::BUILD_VERSION);
    match &findings.provenance {
        Some(p) => {
            let commit = p.git_commit.as_deref().unwrap_or("unknown");
            writeln!(
                out,
                "_Generated by loctree {version} · {} · `{}` · commit {commit}_",
                p.generated_at, p.root
            )
            .unwrap();
        }
        None => {
            writeln!(out, "_Generated by loctree {version}._").unwrap();
        }
    }
    writeln!(out).unwrap();
}

fn scored_twin_count(findings: &AuditFindings) -> usize {
    findings
        .twins
        .iter()
        .filter(|twin| {
            matches!(twin.class, TwinClass::Exact | TwinClass::ShapeSimilar)
                && !omit_from_duplicate_groups(twin)
        })
        .count()
}

/// Map the audit collector onto the canonical scorer. Name collisions,
/// idioms, and role-fenced roots stay off the defect vector.
pub(crate) fn health_metrics_from_audit(findings: &AuditFindings) -> HealthMetrics {
    HealthMetrics {
        breaking_cycles: findings
            .cycles
            .iter()
            .filter(|cycle| cycle.compilability == CycleCompilability::Breaking)
            .count(),
        dead_exports: findings
            .dead_exports
            .iter()
            .filter(|candidate| counts_as_dead_defect(candidate))
            .count(),
        structural_cycles: findings
            .cycles
            .iter()
            .filter(|cycle| cycle.compilability == CycleCompilability::Structural)
            .count(),
        twins_same_language: scored_twin_count(findings),
        files: findings.total_files,
        loc: findings.total_loc,
        ..Default::default()
    }
}

pub(crate) fn audit_health(findings: &AuditFindings) -> HealthScore {
    calculate_health_score(&health_metrics_from_audit(findings))
}

fn write_limit_notice(out: &mut String, total_items: usize, limit: Option<usize>, reason: &str) {
    if let Some(limit) = limit {
        let omitted = total_items.saturating_sub(limit);
        if omitted > 0 {
            writeln!(
                out,
                "- _{} additional items omitted by {}_",
                omitted, reason
            )
            .unwrap();
        }
    }
}

/// Generate full markdown audit report.
/// When `limit` is `None`, the report includes every finding.
pub fn generate_markdown_report(findings: &AuditFindings, limit: Option<usize>) -> String {
    let mut out = String::with_capacity(8192);
    let display_limit = limit.unwrap_or(usize::MAX);

    write_header(&mut out, findings);

    let health = audit_health(findings);
    let name_collisions = findings
        .twins
        .iter()
        .filter(|twin| twin.class == TwinClass::NameCollision)
        .count();
    let breaking_count = findings
        .cycles
        .iter()
        .filter(|cycle| cycle.compilability == CycleCompilability::Breaking)
        .count();
    let structural_count = findings
        .cycles
        .iter()
        .filter(|cycle| cycle.compilability == CycleCompilability::Structural)
        .count();
    let dead_defects = findings
        .dead_exports
        .iter()
        .filter(|candidate| counts_as_dead_defect(candidate))
        .count();
    let actionable_findings = breaking_count
        + structural_count
        + dead_defects
        + scored_twin_count(findings)
        + findings.orphan_files.len()
        + findings.shadow_exports.len();

    writeln!(out, "## Summary\n").unwrap();
    writeln!(out, "| Metric | Value |\n|--------|-------|").unwrap();
    writeln!(out, "| Files | {} |", findings.total_files).unwrap();
    writeln!(out, "| Lines of Code | {} |", findings.total_loc).unwrap();
    writeln!(out, "| Actionable findings | {} |", actionable_findings).unwrap();
    writeln!(
        out,
        "| Name collisions (not scored) | {} |",
        name_collisions
    )
    .unwrap();
    writeln!(
        out,
        "| Health Score (audit basis) | {}/100 |",
        health.health
    )
    .unwrap();
    writeln!(out).unwrap();
    // Named difference, not a silent third number. The audit collector is a
    // strict subset of the structural vector — it has no barrel, cascade or
    // duplicate-export rows at all — so this figure is a different metric and
    // says so, rather than quietly competing with `loct findings --summary`.
    writeln!(
        out,
        "_Health uses the same `health_score` engine as `loct findings`, on a narrower metric: \
the audit collector scores {AUDIT_BASIS}, while `loct findings --summary` and `loct --for-ai` \
score {STRUCTURAL_BASIS}. The two numbers are not comparable and are not meant to match. \
Name collisions and role-fenced roots are not defects._\n"
    )
    .unwrap();

    // Critical section - cycles and high-confidence dead exports
    let breaking_cycles: Vec<_> = findings
        .cycles
        .iter()
        .filter(|c| c.compilability == super::cycles::CycleCompilability::Breaking)
        .collect();

    // New contract: dead exports are delete *candidates*, never verdicts.
    // Only cross-checked high-confidence candidates outside the entry-point
    // fence may appear under CRITICAL, and each carries its evidence.
    let high_confidence_dead: Vec<_> = findings
        .dead_exports
        .iter()
        .filter(|d| d.confidence == "high" && !d.entrypoint)
        .collect();

    if !breaking_cycles.is_empty() || !high_confidence_dead.is_empty() {
        writeln!(out, "## [CRITICAL] Action Required\n").unwrap();

        if !breaking_cycles.is_empty() {
            writeln!(out, "### Breaking Cycles ({})\n", breaking_cycles.len()).unwrap();
            for cycle in breaking_cycles.iter().take(display_limit) {
                writeln!(out, "- [ ] {}", format_cycle(cycle)).unwrap();
            }
            write_limit_notice(&mut out, breaking_cycles.len(), limit, "--limit");
            writeln!(out).unwrap();
        }

        if !high_confidence_dead.is_empty() {
            writeln!(
                out,
                "### Dead Export Candidates - High Confidence ({})\n",
                high_confidence_dead.len()
            )
            .unwrap();
            writeln!(
                out,
                "_Cross-checked candidates (literal layer, symbol graph, entry-point fence). The detector proposes; you decide._\n"
            )
            .unwrap();
            for dead in high_confidence_dead.iter().take(display_limit) {
                writeln!(
                    out,
                    "- [ ] Delete candidate `{}` in {} — {}",
                    dead.symbol,
                    format_symbol_location(&dead.file, dead.line),
                    dead.reason
                )
                .unwrap();
            }
            write_limit_notice(&mut out, high_confidence_dead.len(), limit, "--limit");
            writeln!(out).unwrap();
        }
    }

    // Warnings section
    let structural_cycles: Vec<_> = findings
        .cycles
        .iter()
        .filter(|c| c.compilability == super::cycles::CycleCompilability::Structural)
        .collect();

    // Everything below CRITICAL: degraded candidates (cross-check found
    // literal/string/graph evidence) plus entry-point fenced files.
    let low_confidence_dead: Vec<_> = findings
        .dead_exports
        .iter()
        .filter(|d| d.confidence != "high" || d.entrypoint)
        .collect();

    if !structural_cycles.is_empty()
        || !low_confidence_dead.is_empty()
        || !findings.twins.is_empty()
        || !findings.shadow_exports.is_empty()
    {
        writeln!(out, "## [WARNING] Review Recommended\n").unwrap();

        if !structural_cycles.is_empty() {
            writeln!(out, "### Structural Cycles ({})\n", structural_cycles.len()).unwrap();
            for cycle in structural_cycles.iter().take(display_limit) {
                writeln!(out, "- [ ] {}", format_cycle(cycle)).unwrap();
            }
            write_limit_notice(&mut out, structural_cycles.len(), limit, "--limit");
            writeln!(out).unwrap();
        }

        if !findings.twins.is_empty() {
            writeln!(out, "### Duplicate Symbols ({})\n", findings.twins.len()).unwrap();
            write_twins_by_class(&mut out, &findings.twins, limit, display_limit);
        }

        if !findings.shadow_exports.is_empty() {
            writeln!(
                out,
                "### Shadow Exports ({})\n",
                findings.shadow_exports.len()
            )
            .unwrap();
            writeln!(out, "_Same symbol with some dead instances_\n").unwrap();
            for shadow in findings.shadow_exports.iter().take(display_limit) {
                writeln!(
                    out,
                    "- [ ] `{}`: {}/{} locations dead",
                    shadow.name, shadow.dead_locations, shadow.total_locations
                )
                .unwrap();
            }
            write_limit_notice(&mut out, findings.shadow_exports.len(), limit, "--limit");
            writeln!(out).unwrap();
        }

        if !low_confidence_dead.is_empty() {
            writeln!(
                out,
                "### Dead Exports - Review Needed ({})\n",
                low_confidence_dead.len()
            )
            .unwrap();
            for dead in low_confidence_dead.iter().take(display_limit) {
                writeln!(
                    out,
                    "- [ ] Review `{}` in {} — {} (confidence: {})",
                    dead.symbol,
                    format_symbol_location(&dead.file, dead.line),
                    dead.reason,
                    dead.confidence
                )
                .unwrap();
            }
            write_limit_notice(&mut out, low_confidence_dead.len(), limit, "--limit");
            writeln!(out).unwrap();
        }
    }

    let actionable_crowds: Vec<&Crowd> = findings
        .crowds
        .iter()
        .filter(|crowd| !crowd.issues.is_empty())
        .collect();
    let has_inventory = !findings.orphan_files.is_empty()
        || !findings.artifact_orphans.is_empty()
        || !findings.entrypoint_orphans.is_empty()
        || !findings.test_orphans.is_empty()
        || !findings.script_orphans.is_empty()
        || !findings.doc_orphans.is_empty()
        || !findings.manifest_orphans.is_empty()
        || !actionable_crowds.is_empty();

    if has_inventory {
        writeln!(out, "## [INFO] Inventory (not findings)\n").unwrap();
        writeln!(
            out,
            "_Role-fenced roots, artifacts, and token clusters. Classification is correct; these are not orphans to review. Rosters live in `findings.json`._\n"
        )
        .unwrap();

        if !findings.orphan_files.is_empty() {
            let total_orphan_loc: usize = findings.orphan_files.iter().map(|f| f.loc).sum();
            writeln!(
                out,
                "### Actionable orphans ({} files, {} LOC)\n",
                findings.orphan_files.len(),
                total_orphan_loc
            )
            .unwrap();
            writeln!(
                out,
                "_Files with no importers after role/artifact/entrypoint fences. Roster: `findings.json`._\n"
            )
            .unwrap();
        }

        writeln!(out, "### Graph roots (not orphans)\n").unwrap();
        write_role_orphan_rollup(
            &mut out,
            "Runtime entrypoints",
            &findings.entrypoint_orphans,
        );
        write_role_orphan_rollup(&mut out, "Test roots", &findings.test_orphans);
        write_role_orphan_rollup(&mut out, "Script roots", &findings.script_orphans);
        write_role_orphan_rollup(&mut out, "Doc roots", &findings.doc_orphans);
        write_role_orphan_rollup(&mut out, "Manifest roots", &findings.manifest_orphans);
        write_role_orphan_rollup(&mut out, "Artifact / excluded", &findings.artifact_orphans);
        writeln!(out).unwrap();

        if !actionable_crowds.is_empty() {
            writeln!(
                out,
                "### Filename token clusters with issues ({})\n",
                actionable_crowds.len()
            )
            .unwrap();
            writeln!(
                out,
                "_Not coupling. Token-frequency clusters that already have detected issues. Roster: `findings.json`._\n"
            )
            .unwrap();
            for crowd in actionable_crowds.iter().take(display_limit) {
                writeln!(
                    out,
                    "- `{}`: {} files · {} issues",
                    crowd.pattern,
                    crowd.members.len(),
                    crowd.issues.len()
                )
                .unwrap();
            }
            write_limit_notice(&mut out, actionable_crowds.len(), limit, "--limit");
            writeln!(out).unwrap();
        }
    }

    writeln!(out, "## [QUICK WIN] Easy Improvements\n").unwrap();
    let quick_wins = calculate_quick_wins(findings);
    if quick_wins.is_empty() {
        writeln!(
            out,
            "_Nothing cheap to do. Remaining work is in [CRITICAL] / [WARNING], or the tree is clean._\n"
        )
        .unwrap();
    } else {
        for (i, win) in quick_wins.iter().enumerate().take(5) {
            writeln!(out, "{}. {}", i + 1, win).unwrap();
        }
        write_limit_notice(&mut out, quick_wins.len(), Some(5), "quick-win summary cap");
        writeln!(out).unwrap();
    }

    out
}

/// Generate actionable todo checklist only.
pub fn generate_todos(findings: &AuditFindings, limit: Option<usize>) -> String {
    let mut out = String::with_capacity(4096);
    let display_limit = limit.unwrap_or(usize::MAX);

    let today = chrono::Local::now().format("%Y-%m-%d");
    writeln!(out, "# Audit Todos ({})\n", today).unwrap();

    // Critical
    let breaking_cycles: Vec<_> = findings
        .cycles
        .iter()
        .filter(|c| c.compilability == super::cycles::CycleCompilability::Breaking)
        .collect();

    // Same contract as the markdown report: cross-checked candidates only,
    // entry-point fence excludes runtime entries from the critical list.
    let high_confidence_dead: Vec<_> = findings
        .dead_exports
        .iter()
        .filter(|d| d.confidence == "high" && !d.entrypoint)
        .collect();

    if !breaking_cycles.is_empty() || !high_confidence_dead.is_empty() {
        writeln!(out, "## Critical\n").unwrap();

        for cycle in breaking_cycles.iter().take(display_limit) {
            writeln!(out, "- [ ] Break cycle: {}", format_cycle(cycle)).unwrap();
        }
        write_limit_notice(&mut out, breaking_cycles.len(), limit, "--limit");

        for dead in high_confidence_dead.iter().take(display_limit) {
            writeln!(
                out,
                "- [ ] Review delete candidate `{}` in {} — {}",
                dead.symbol,
                format_symbol_location(&dead.file, dead.line),
                dead.reason
            )
            .unwrap();
        }
        write_limit_notice(&mut out, high_confidence_dead.len(), limit, "--limit");
        writeln!(out).unwrap();
    }

    // Warnings
    let structural_cycles: Vec<_> = findings
        .cycles
        .iter()
        .filter(|c| c.compilability == super::cycles::CycleCompilability::Structural)
        .collect();

    if !structural_cycles.is_empty() || !findings.twins.is_empty() {
        writeln!(out, "## Warnings\n").unwrap();

        for cycle in structural_cycles.iter().take(display_limit) {
            writeln!(out, "- [ ] Review cycle: {}", format_cycle(cycle)).unwrap();
        }
        write_limit_notice(&mut out, structural_cycles.len(), limit, "--limit");

        // "Consolidate" is earned by shape evidence (class EXACT) only.
        let exact_twins: Vec<_> = findings
            .twins
            .iter()
            .filter(|t| t.class == TwinClass::Exact)
            .collect();
        for twin in exact_twins.iter().take(display_limit) {
            writeln!(
                out,
                "- [ ] Consolidate `{}` ({} locations)",
                twin.name,
                twin.locations.len()
            )
            .unwrap();
        }
        write_limit_notice(&mut out, exact_twins.len(), limit, "--limit");

        // Shape-similar twins: review, never auto-consolidate.
        let shape_twins: Vec<_> = findings
            .twins
            .iter()
            .filter(|t| t.class == TwinClass::ShapeSimilar)
            .collect();
        for twin in shape_twins.iter().take(display_limit) {
            writeln!(
                out,
                "- [ ] Review similar shapes of `{}` ({} locations)",
                twin.name,
                twin.locations.len()
            )
            .unwrap();
        }
        write_limit_notice(&mut out, shape_twins.len(), limit, "--limit");

        // Name collisions aggregate per file group: one systemic todo per
        // twin-pair, not one checkbox per shared symbol name.
        let collision_twins: Vec<&ExactTwin> = findings
            .twins
            .iter()
            .filter(|t| t.class == TwinClass::NameCollision)
            .collect();
        let collision_groups = collision_file_groups(&collision_twins);
        for (files, symbols) in collision_groups.iter().take(display_limit) {
            if symbols.len() > 1 {
                writeln!(
                    out,
                    "- [ ] Review systemic twin-pair {} ({} shared symbol names)",
                    files
                        .iter()
                        .map(|f| format!("`{}`", f))
                        .collect::<Vec<_>>()
                        .join(" ↔ "),
                    symbols.len()
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "- [ ] Review name collision `{}` ({} locations)",
                    symbols[0],
                    files.len()
                )
                .unwrap();
            }
        }
        write_limit_notice(&mut out, collision_groups.len(), limit, "--limit");
        writeln!(out).unwrap();
    }

    writeln!(out, "## Quick Wins\n").unwrap();
    let quick_wins = calculate_quick_wins(findings);
    if quick_wins.is_empty() {
        writeln!(
            out,
            "_Nothing cheap to do. Remaining work is in Critical / Warnings, or the tree is clean._\n"
        )
        .unwrap();
    } else {
        for win in quick_wins.iter().take(5) {
            writeln!(out, "- [ ] {}", win).unwrap();
        }
        write_limit_notice(&mut out, quick_wins.len(), Some(5), "quick-win summary cap");
    }

    out
}

/// Format a cycle for display
fn format_cycle(cycle: &ClassifiedCycle) -> String {
    cycle.nodes.join(" → ")
}

/// Aggregate NAME_COLLISION twins per file group: the same pair of files
/// sharing 30 symbol names is ONE systemic finding ("twin-pair"), not 30
/// checkboxes. Returns (sorted file list, symbols) sorted by symbol count
/// descending, then by file list for determinism.
fn collision_file_groups<'a>(twins: &[&'a ExactTwin]) -> Vec<(Vec<String>, Vec<&'a str>)> {
    let mut groups: std::collections::BTreeMap<Vec<String>, Vec<&'a str>> =
        std::collections::BTreeMap::new();
    for twin in twins {
        let mut files: Vec<String> = twin.locations.iter().map(|l| l.file_path.clone()).collect();
        files.sort();
        files.dedup();
        groups.entry(files).or_default().push(twin.name.as_str());
    }
    let mut out: Vec<(Vec<String>, Vec<&'a str>)> = groups.into_iter().collect();
    out.sort_by(|a, b| b.1.len().cmp(&a.1.len()).then_with(|| a.0.cmp(&b.0)));
    out
}

/// Write the Duplicate Symbols section grouped by shape-evidence class.
///
/// - EXACT: actionable consolidation checkboxes.
/// - SHAPE_SIMILAR: review checkboxes (no "Consolidate" wording).
/// - NAME_COLLISION: aggregated per file pair — systemic twin-pairs.
/// - IDIOM: convention summary, no checkboxes.
fn write_twins_by_class(
    out: &mut String,
    twins: &[ExactTwin],
    limit: Option<usize>,
    display_limit: usize,
) {
    let exact: Vec<&ExactTwin> = twins
        .iter()
        .filter(|t| t.class == TwinClass::Exact)
        .collect();
    let shape: Vec<&ExactTwin> = twins
        .iter()
        .filter(|t| t.class == TwinClass::ShapeSimilar)
        .collect();
    let collisions: Vec<&ExactTwin> = twins
        .iter()
        .filter(|t| t.class == TwinClass::NameCollision)
        .collect();
    let idioms: Vec<&ExactTwin> = twins
        .iter()
        .filter(|t| t.class == TwinClass::Idiom)
        .collect();

    let twin_line = |twin: &ExactTwin| {
        let locations: Vec<_> = twin
            .locations
            .iter()
            .map(|l| l.file_path.as_str())
            .collect();
        format!(
            "`{}`: {} locations ({})",
            twin.name,
            twin.locations.len(),
            locations.join(", ")
        )
    };

    if !exact.is_empty() {
        writeln!(
            out,
            "#### EXACT — identical shape, consolidate ({})\n",
            exact.len()
        )
        .unwrap();
        for twin in exact.iter().take(display_limit) {
            writeln!(out, "- [ ] Consolidate {}", twin_line(twin)).unwrap();
        }
        write_limit_notice(out, exact.len(), limit, "--limit");
        writeln!(out).unwrap();
    }

    if !shape.is_empty() {
        writeln!(
            out,
            "#### SHAPE_SIMILAR — overlapping shape, review ({})\n",
            shape.len()
        )
        .unwrap();
        for twin in shape.iter().take(display_limit) {
            writeln!(out, "- [ ] Review {}", twin_line(twin)).unwrap();
        }
        write_limit_notice(out, shape.len(), limit, "--limit");
        writeln!(out).unwrap();
    }

    if !collisions.is_empty() {
        let groups = collision_file_groups(&collisions);
        writeln!(
            out,
            "#### NAME_COLLISION — informational ({} symbols across {} file groups)\n",
            collisions.len(),
            groups.len()
        )
        .unwrap();
        writeln!(
            out,
            "_Same name, no shape evidence of duplication. Do not consolidate blindly._\n"
        )
        .unwrap();
        for (files, symbols) in groups.iter().take(display_limit) {
            if symbols.len() > 1 {
                let mut examples: Vec<&str> = symbols.iter().take(3).copied().collect();
                examples.sort_unstable();
                writeln!(
                    out,
                    "- [ ] Systemic twin-pair {}: {} shared symbol names (e.g. {})",
                    files
                        .iter()
                        .map(|f| format!("`{}`", f))
                        .collect::<Vec<_>>()
                        .join(" ↔ "),
                    symbols.len(),
                    examples.join(", ")
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "- [ ] `{}`: name collision across {}",
                    symbols[0],
                    files
                        .iter()
                        .map(|f| format!("`{}`", f))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
                .unwrap();
            }
        }
        write_limit_notice(out, groups.len(), limit, "--limit");
        writeln!(out).unwrap();
    }

    if !idioms.is_empty() {
        let names: Vec<&str> = idioms.iter().take(5).map(|t| t.name.as_str()).collect();
        writeln!(
            out,
            "#### IDIOM — language convention, no action ({}): {}\n",
            idioms.len(),
            names.join(", ")
        )
        .unwrap();
    }
}

/// Calculate quick wins - easy fixes with high impact
fn calculate_quick_wins(findings: &AuditFindings) -> Vec<String> {
    let mut wins = Vec::new();

    // Group dead exports by directory
    let mut by_dir: std::collections::HashMap<String, (usize, usize)> =
        std::collections::HashMap::new();
    for dead in &findings.dead_exports {
        if dead.confidence == "high" && !dead.entrypoint {
            let dir = std::path::Path::new(&dead.file)
                .parent()
                .map(|p| p.to_string_lossy().to_string())
                .unwrap_or_else(|| ".".to_string());
            let entry = by_dir.entry(dir).or_insert((0, 0));
            entry.0 += 1;
            // Estimate ~10 LOC per dead export
            entry.1 += 10;
        }
    }

    // Sort by count and take top directories
    let mut dirs: Vec<_> = by_dir.into_iter().collect();
    dirs.sort_by_key(|b| std::cmp::Reverse(b.1.0));

    for (dir, (count, loc_estimate)) in dirs.into_iter().take(3) {
        if count >= 3 {
            wins.push(format!(
                "Clean `{}`: remove {} dead exports (~{} LOC)",
                dir, count, loc_estimate
            ));
        }
    }

    // Breaking cycles are always high priority
    let breaking: Vec<_> = findings
        .cycles
        .iter()
        .filter(|c| c.compilability == super::cycles::CycleCompilability::Breaking)
        .take(2)
        .collect();

    for cycle in breaking {
        wins.push(format!(
            "Break cycle in `{}`",
            cycle.nodes.first().unwrap_or(&"unknown".to_string())
        ));
    }

    wins
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dead_export(symbol: &str, line: usize) -> DeadExport {
        DeadExport {
            file: "src/lib.rs".into(),
            symbol: symbol.into(),
            line: Some(line),
            confidence: "high".into(),
            reason: "unused export".into(),
            open_url: None,
            is_test: false,
            action: "delete_candidate".to_string(),
            entrypoint: false,
        }
    }

    #[test]
    fn test_empty_findings_generates_report() {
        let findings = AuditFindings::default();
        let report = generate_markdown_report(&findings, None);
        assert!(report.contains("# Codebase Audit Report"));
        assert!(report.contains("Health Score (audit basis) | 100/100"));
    }

    #[test]
    fn test_todos_output() {
        let findings = AuditFindings::default();
        let todos = generate_todos(&findings, None);
        assert!(todos.contains("# Audit Todos"));
    }

    #[test]
    fn test_markdown_report_is_full_by_default() {
        let findings = AuditFindings {
            dead_exports: (0..3)
                .map(|idx| dead_export(&format!("dead_{idx}"), idx + 1))
                .collect(),
            ..AuditFindings::default()
        };

        let report = generate_markdown_report(&findings, None);

        assert!(report.contains("dead_0"));
        assert!(report.contains("dead_1"));
        assert!(report.contains("dead_2"));
        assert!(!report.contains("omitted by --limit"));
    }

    #[test]
    fn test_markdown_report_calls_out_explicit_limit() {
        let findings = AuditFindings {
            dead_exports: (0..3)
                .map(|idx| dead_export(&format!("dead_{idx}"), idx + 1))
                .collect(),
            ..AuditFindings::default()
        };

        let report = generate_markdown_report(&findings, Some(2));

        assert!(report.contains("dead_0"));
        assert!(report.contains("dead_1"));
        assert!(!report.contains("dead_2"));
        assert!(report.contains("1 additional items omitted by --limit"));
    }

    #[test]
    fn test_todos_call_out_explicit_limit() {
        let findings = AuditFindings {
            dead_exports: (0..3)
                .map(|idx| dead_export(&format!("dead_{idx}"), idx + 1))
                .collect(),
            ..AuditFindings::default()
        };

        let todos = generate_todos(&findings, Some(2));

        assert!(todos.contains("dead_0"));
        assert!(todos.contains("dead_1"));
        assert!(!todos.contains("dead_2"));
        assert!(todos.contains("1 additional items omitted by --limit"));
    }

    fn twin(name: &str, class: TwinClass, files: &[&str]) -> ExactTwin {
        use super::super::twins::{TwinClassification, TwinLocation};
        ExactTwin {
            name: name.to_string(),
            locations: files
                .iter()
                .map(|f| TwinLocation {
                    file_path: f.to_string(),
                    line: 1,
                    kind: "function".to_string(),
                    import_count: 0,
                    is_canonical: false,
                    signature_fingerprint: None,
                })
                .collect(),
            signature_similarity: None,
            classification: match class {
                TwinClass::Exact | TwinClass::ShapeSimilar => TwinClassification::Duplicate,
                _ => TwinClassification::Namesake,
            },
            class,
            shape_match: false,
            single_module_target: false,
            exclude_from_score: false,
        }
    }

    /// Golden: 30 NAME_COLLISION symbols shared between the same two files
    /// (pack.rs ↔ context/mod.rs smear) collapse to ONE systemic twin-pair
    /// row — not 30 checkboxes — in both the markdown report and the todos.
    #[test]
    fn test_name_collision_pairs_aggregate_per_file_pair() {
        let findings = AuditFindings {
            twins: (0..30)
                .map(|idx| {
                    twin(
                        &format!("shared_symbol_{idx}"),
                        TwinClass::NameCollision,
                        &["src/pack.rs", "src/context/mod.rs"],
                    )
                })
                .collect(),
            ..AuditFindings::default()
        };

        let report = generate_markdown_report(&findings, None);
        let pair_rows = report
            .lines()
            .filter(|l| l.contains("Systemic twin-pair"))
            .count();
        assert_eq!(
            pair_rows, 1,
            "expected ONE aggregated twin-pair row:\n{report}"
        );
        assert!(report.contains("30 shared symbol names"), "{report}");
        assert!(
            report.contains("`src/context/mod.rs` ↔ `src/pack.rs`"),
            "{report}"
        );
        // No consolidation advice for name collisions.
        assert!(!report.contains("Consolidate"), "{report}");

        let todos = generate_todos(&findings, None);
        let todo_rows = todos
            .lines()
            .filter(|l| l.contains("systemic twin-pair"))
            .count();
        assert_eq!(todo_rows, 1, "expected ONE aggregated todo row:\n{todos}");
        assert!(!todos.contains("Consolidate"), "{todos}");
    }

    /// "Consolidate" appears exclusively for class EXACT.
    #[test]
    fn test_consolidate_only_for_exact_class() {
        let findings = AuditFindings {
            twins: vec![
                twin("render_widget", TwinClass::Exact, &["src/a.rs", "src/b.rs"]),
                twin(
                    "register",
                    TwinClass::NameCollision,
                    &["src/c.rs", "src/d.rs"],
                ),
                twin("from_env", TwinClass::Idiom, &["src/e.rs", "src/f.rs"]),
            ],
            ..AuditFindings::default()
        };

        let report = generate_markdown_report(&findings, None);
        let consolidate_lines: Vec<_> = report
            .lines()
            .filter(|l| l.contains("Consolidate"))
            .collect();
        assert!(
            consolidate_lines
                .iter()
                .all(|l| l.contains("render_widget")),
            "Consolidate must only mention the EXACT twin:\n{report}"
        );
        assert!(report.contains("EXACT"), "{report}");
        assert!(report.contains("NAME_COLLISION"), "{report}");
        assert!(report.contains("IDIOM"), "{report}");

        let todos = generate_todos(&findings, None);
        let todo_consolidate: Vec<_> = todos
            .lines()
            .filter(|l| l.contains("Consolidate"))
            .collect();
        assert_eq!(todo_consolidate.len(), 1, "{todos}");
        assert!(todo_consolidate[0].contains("render_widget"), "{todos}");
    }

    #[test]
    fn test_header_closes_emphasis_and_carries_provenance() {
        let findings = AuditFindings {
            provenance: Some(ReportProvenance {
                version: "0.14.2+g9b3a958c".into(),
                generated_at: "2026-08-14T12:46:42Z".into(),
                root: "/repo".into(),
                git_commit: Some("9b3a958c".into()),
            }),
            ..AuditFindings::default()
        };
        let report = generate_markdown_report(&findings, None);
        let header = report
            .lines()
            .find(|line| line.contains("Generated by loctree"))
            .expect("header line");
        assert!(
            header.starts_with('_') && header.ends_with('_'),
            "italic must be closed:\n{header}"
        );
        assert!(header.contains("0.14.2+g9b3a958c"), "{header}");
        assert!(header.contains("2026-08-14T12:46:42Z"), "{header}");
        assert!(header.contains("`/repo`"), "{header}");
        assert!(header.contains("commit 9b3a958c"), "{header}");
        assert!(!header.contains("loctree-"), "{header}");
    }

    #[test]
    fn test_empty_report_always_has_quick_wins_and_version() {
        let report = generate_markdown_report(&AuditFindings::default(), None);
        assert!(report.contains("[QUICK WIN]"), "{report}");
        assert!(report.contains("Nothing cheap to do"), "{report}");
        assert!(report.contains("Generated by loctree"), "{report}");
        assert!(report.contains(crate::BUILD_VERSION), "{report}");
        let todos = generate_todos(&AuditFindings::default(), None);
        assert!(todos.contains("## Quick Wins"), "{todos}");
        assert!(todos.contains("Nothing cheap to do"), "{todos}");
    }

    #[test]
    fn test_info_is_rollup_not_roster() {
        let findings = AuditFindings {
            doc_orphans: (0..400)
                .map(|idx| OrphanFile {
                    path: format!("docs/n{idx}.md"),
                    loc: 4,
                })
                .collect(),
            test_orphans: vec![OrphanFile {
                path: "tests/foo.rs".into(),
                loc: 12,
            }],
            ..AuditFindings::default()
        };
        let report = generate_markdown_report(&findings, None);
        assert!(
            report.contains("Doc roots: 400 files, 1600 LOC"),
            "{report}"
        );
        assert!(report.contains("Test roots: 1 files, 12 LOC"), "{report}");
        assert!(
            !report.contains("docs/n0.md"),
            "INFO must not roster files:\n{report}"
        );
        assert!(
            !report.contains("tests/foo.rs"),
            "INFO must not roster files:\n{report}"
        );
        assert!(report.contains("findings.json"), "{report}");
    }

    #[test]
    fn test_warning_dead_export_includes_reason_and_omits_line_zero() {
        let findings = AuditFindings {
            dead_exports: vec![DeadExport {
                file: "__init__.py".into(),
                symbol: "helper".into(),
                line: None,
                confidence: "medium".into(),
                reason: "unresolved import graph".into(),
                open_url: None,
                is_test: false,
                action: "review".into(),
                entrypoint: false,
            }],
            ..AuditFindings::default()
        };
        let report = generate_markdown_report(&findings, None);
        assert!(report.contains("unresolved import graph"), "{report}");
        assert!(report.contains("confidence: medium"), "{report}");
        assert!(
            !report.contains(":0"),
            "unknown line must not render as :0:\n{report}"
        );
        assert!(report.contains("in __init__.py —"), "{report}");
    }

    #[test]
    fn test_name_collisions_do_not_saturate_health() {
        let collisions = AuditFindings {
            twins: (0..267)
                .map(|idx| {
                    twin(
                        &format!("shared_{idx}"),
                        TwinClass::NameCollision,
                        &["src/a.rs", "src/b.rs"],
                    )
                })
                .collect(),
            total_files: 1000,
            total_loc: 80_000,
            ..AuditFindings::default()
        };
        let exact = AuditFindings {
            twins: (0..10)
                .map(|idx| {
                    twin(
                        &format!("dup_{idx}"),
                        TwinClass::Exact,
                        &["src/a.rs", "src/b.rs"],
                    )
                })
                .collect(),
            total_files: 1000,
            total_loc: 80_000,
            ..AuditFindings::default()
        };
        let collision_score = audit_health(&collisions).health;
        let exact_score = audit_health(&exact).health;
        assert_eq!(
            collision_score, 100,
            "NAME_COLLISION is informational and must not move health"
        );
        assert!(
            exact_score < collision_score,
            "10 EXACT twins must score worse than 267 collisions: exact={exact_score} collisions={collision_score}"
        );
        let report = generate_markdown_report(&collisions, None);
        assert!(
            report.contains("| Name collisions (not scored) | 267 |"),
            "{report}"
        );
        assert!(report.contains("| Actionable findings | 0 |"), "{report}");
    }

    #[test]
    fn test_crowds_without_issues_are_omitted() {
        use super::super::crowd::types::{Crowd, CrowdIssue, CrowdMember, MatchReason};
        let silent = Crowd {
            pattern: "test".into(),
            members: (0..50)
                .map(|idx| CrowdMember {
                    file: format!("t{idx}.rs"),
                    match_reason: MatchReason::NameMatch {
                        matched: "test".into(),
                    },
                    importer_count: 0,
                    similarity_scores: Vec::new(),
                    is_test: true,
                })
                .collect(),
            score: 1.0,
            issues: Vec::new(),
            context_type: None,
        };
        let noisy = Crowd {
            pattern: "auth".into(),
            members: vec![CrowdMember {
                file: "auth.rs".into(),
                match_reason: MatchReason::NameMatch {
                    matched: "auth".into(),
                },
                importer_count: 4,
                similarity_scores: Vec::new(),
                is_test: false,
            }],
            score: 6.0,
            issues: vec![CrowdIssue::Fragmentation {
                categories: vec!["login".into(), "session".into()],
            }],
            context_type: None,
        };
        let report = generate_markdown_report(
            &AuditFindings {
                crowds: vec![silent, noisy],
                ..AuditFindings::default()
            },
            None,
        );
        assert!(
            report.contains("Filename token clusters with issues (1)"),
            "{report}"
        );
        assert!(report.contains("`auth`: 1 files · 1 issues"), "{report}");
        assert!(!report.contains("`test`:"), "{report}");
        assert!(!report.contains("high coupling"), "{report}");
    }

    /// The audit collector scores a strict subset of the structural vector, so
    /// its number legitimately differs from `loct findings --summary`. What is
    /// not legitimate is a *silent* difference: the report must name both bases
    /// so a reader can tell "different metric" from "disagreeing measurement".
    /// This is the second half of one-number-one-truth — the first half is
    /// `tests/health_truth.rs`, which pins the surfaces that must agree.
    #[test]
    fn test_audit_report_names_its_narrower_basis() {
        let report = generate_markdown_report(&AuditFindings::default(), None);
        assert!(
            report.contains("Health Score (audit basis)"),
            "the health row must be labelled as the audit basis: {report}"
        );
        assert!(
            report.contains(AUDIT_BASIS),
            "the report must name what the audit collector scores: {report}"
        );
        assert!(
            report.contains(STRUCTURAL_BASIS),
            "the report must name what it is NOT comparable to: {report}"
        );
        assert!(
            report.contains("not comparable"),
            "the difference must be stated, not left for the reader to infer: {report}"
        );
    }

    #[test]
    fn test_audit_health_matches_canonical_scorer() {
        let findings = AuditFindings {
            dead_exports: vec![dead_export("gone", 4)],
            total_files: 40,
            total_loc: 4_000,
            ..AuditFindings::default()
        };
        let via_audit = audit_health(&findings);
        let via_engine = calculate_health_score(&health_metrics_from_audit(&findings));
        assert_eq!(via_audit.health, via_engine.health);
        assert_eq!(via_audit.details.high.count, 1);
    }
}
